### ISSUE TITLE
fullpage editing problem

### ISSUE THREAD

**Issue by selvampgp** [andykirk/CKEditorFootnotes#13]
while fullpage option is true ...unable to add footer ..it showing some errors in console..

**Comment by andykirk** [comment]
Hi,
I'm afraid I can't replicate the problem.
It's possible that it was inadvertently fixed in one of the recent updates. I haven't created a new release yet, but if you can use the plugin and dialog files from the master branch and can still reproduce the problem, please reopen this issue with a few more specifics:

* Your config (to indicate any settings or plugins that may be conflicting)
* A paste of the error message you're seeing

Thanks,
Andy
